/**
 * Open Wonderland
 *
 * Copyright (c) 2010, Open Wonderland Foundation, All Rights Reserved
 *
 * Redistributions in source code form must reproduce the above
 * copyright and this condition.
 *
 * The contents of this file are subject to the GNU General Public
 * License, Version 2 (the "License"); you may not use this file
 * except in compliance with the License. A copy of the License is
 * available at http://www.opensource.org/licenses/gpl-license.php.
 *
 * The Open Wonderland Foundation designates this particular file as
 * subject to the "Classpath" exception as provided by the Open Wonderland
 * Foundation in the License file that accompanied this code.
 */

package org.jdesktop.wonderland.modules.grouptools.client;

import java.util.HashMap;
import javax.swing.JPanel;
import org.jdesktop.wonderland.client.cell.Cell;
import org.jdesktop.wonderland.modules.audiomanager.client.PresenceControls;
import org.jdesktop.wonderland.modules.audiomanager.client.UserListHUDPanel;

/**
 *
 * @author Ryan Babiuch
 */
public class UserHUDPanel extends javax.swing.JPanel {

    /** Creates new form UserHUDPanel */
    private PresenceControls pc;
    private Cell cell;
  //  private HashMap<String, JPanel> stringToPanel;
    private UserListHUDPanel userListHUDPanel;
    private GroupListHUDPanel groupListHUDPanel;
    private TestPanel testPanel;
    public UserHUDPanel() {
        initComponents();
    //    stringToPanel = new HashMap<String, JPanel>();
        groupListHUDPanel = new GroupListHUDPanel();
        testPanel = new TestPanel();
        jTabbedPane1.addTab("Groups", groupListHUDPanel);
        //contentPanel = testPanel;// = new UserListHUDPanel(pc, cell);
       // contentPanel.setVisible(true);
    }
/*
    public JPanel getContentPanel() {
        return contentPanel;
    }

    public void setContentPanel(JPanel panel) {
        this.contentPanel = panel;
    }
*/
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

}
