/**
 * Project Wonderland
 *
 * Copyright (c) 2004-2009, Sun Microsystems, Inc., All Rights Reserved
 *
 * Redistributions in source code form must reproduce the above
 * copyright and this condition.
 *
 * The contents of this file are subject to the GNU General Public
 * License, Version 2 (the "License"); you may not use this file
 * except in compliance with the License. A copy of the License is
 * available at http://www.opensource.org/licenses/gpl-license.php.
 *
 * Sun designates this particular file as subject to the "Classpath"
 * exception as provided by Sun in the License file that accompanied
 * this code.
 */
/*
 * LoopSegmentEditor.java
 *
 * Created on Aug 14, 2009, 6:56:30 AM
 */

package org.jdesktop.wonderland.modules.marbleous.client.ui;

import org.jdesktop.wonderland.modules.marbleous.common.LoopSegmentSettings;
import org.jdesktop.wonderland.modules.marbleous.common.LoopTrackSegmentType;
import org.jdesktop.wonderland.modules.marbleous.common.TrackSegment;

/**
 *
 * @author paulby
 */
public class LoopSegmentEditor extends SegmentEditor {

    /** Creates new form LoopSegmentEditor */
    public LoopSegmentEditor() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        loopRadiusTF = new javax.swing.JTextField();

        setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Loop Radius :");
        add(jLabel1, new java.awt.GridBagConstraints());

        loopRadiusTF.setText("jTextField1");
        loopRadiusTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loopRadiusTFActionPerformed(evt);
            }
        });
        add(loopRadiusTF, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void loopRadiusTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loopRadiusTFActionPerformed
        LoopSegmentSettings s = (LoopSegmentSettings) segment.getSegmentSettings();
        s.setRadius(Float.parseFloat(loopRadiusTF.getText()));

        // TODO notify model that there is an update
        LoopTrackSegmentType t = new LoopTrackSegmentType();
        t.updateSegment(segment, s);
        notifySegmentChanged();
    }//GEN-LAST:event_loopRadiusTFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField loopRadiusTF;
    // End of variables declaration//GEN-END:variables

    public void setSegment(TrackSegment segment) {
        this.segment = segment;
        LoopSegmentSettings s = (LoopSegmentSettings) segment.getSegmentSettings();
        loopRadiusTF.setText(Float.toString(s.getRadius()));
    }


}
