/**
 * Open Wonderland
 *
 * Copyright (c) 2010, Open Wonderland Foundation, All Rights Reserved
 *
 * Redistributions in source code form must reproduce the above
 * copyright and this condition.
 *
 * The contents of this file are subject to the GNU General Public
 * License, Version 2 (the "License"); you may not use this file
 * except in compliance with the License. A copy of the License is
 * available at http://www.opensource.org/licenses/gpl-license.php.
 *
 * The Open Wonderland Foundation designates this particular file as
 * subject to the "Classpath" exception as provided by the Open Wonderland
 * Foundation in the License file that accompanied this code.
 */
package org.jdesktop.wonderland.modules.tightvncviewer.client;

import java.awt.dnd.DnDConstants;
import java.awt.dnd.DragSource;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Map;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import org.jdesktop.wonderland.modules.tightvncviewer.common.TightVNCViewerState;

/**
 * VNC viewer control panel.
 *
 * @author nsimpson
 */
public class TightVNCViewerControlPanel extends javax.swing.JPanel {

    private static final Logger logger = Logger.getLogger(TightVNCViewerControlPanel.class.getName());
    protected boolean fillMode = false;
    protected ArrayList<TightVNCViewerToolListener> cellMenuListeners = new ArrayList();
    protected Map toolMappings;
    protected TightVNCViewerWindow window;
    protected TightVNCViewerDragGestureListener gestureListener;
    private ImageIcon disconnectIcon;

    public TightVNCViewerControlPanel(TightVNCViewerWindow window) {
        this.window = window;
        initComponents();
        initListeners();
        disconnectIcon = new ImageIcon(getClass().getResource("/org/jdesktop/wonderland/modules/tightvncviewer/client/resources/TightVNCViewerClose32x32.png"));
    }

    /**
     * Add a listener for tool events
     * @param listener a listener to receive tool events
     */
    public void addCellMenuListener(TightVNCViewerToolListener listener) {
        cellMenuListeners.add(listener);
    }

    /**
     * Remove a listener for tool events
     * @param listener the listener to remove
     */
    public void removeCellMenuListener(TightVNCViewerToolListener listener) {
        cellMenuListeners.remove(listener);
    }

    /**
     *  Initialize drag and drop listener
     */
    private void initListeners() {
        DragSource ds = DragSource.getDefaultDragSource();
        gestureListener = new TightVNCViewerDragGestureListener(window);
        ds.createDefaultDragGestureRecognizer(dragHUDButton,
                DnDConstants.ACTION_COPY_OR_MOVE, gestureListener);
    }

    /**
     * Update control panel mode to reflect state of player
     * @param state the state of the player
     */
    public void setMode(TightVNCViewerState state) {
        switch (state) {
            default:
                break;
        }
    }

    /**
     * Gets whether a button is depressed
     * @param button the button to check
     * @return true if the button is depressed, false otherwise
     */
    public boolean isButtonDepressed(JButton button) {
        return button.isBorderPainted();
    }

    /**
     * Depress/undepress a button (for displaying a selected mode)
     * @param button the button to depress
     * @param depress true to depress a button, false to undepress
     */
    public void depressButton(JButton button, boolean depress) {
        button.setBorderPainted(depress);
    }

    /**
     * Set the state of the on-HUD button
     * @param onHUD true if the control panel is displayed on-HUD, false
     * if in-world
     */
    public void setOnHUD(boolean onHUD) {
        if (onHUD) {
            toggleHUDButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/jdesktop/wonderland/modules/tightvncviewer/client/resources/TightVNCViewerDock32x32.png")));
        } else {
            toggleHUDButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/jdesktop/wonderland/modules/tightvncviewer/client/resources/TightVNCViewerUndock32x32.png")));
        }
    }

    /**
     * Set the state of the sync button
     * @param synced true if synced, false if not
     */
    public void setSynced(boolean synced) {
        if (synced) {
            syncHUDButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/jdesktop/wonderland/modules/tightvncviewer/client/resources/TightVNCViewerSyncedYes32x32.png")));
        } else {
            syncHUDButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/jdesktop/wonderland/modules/tightvncviewer/client/resources/TightVNCViewerSyncedNo32x32.png")));
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toggleHUDButton = new javax.swing.JButton();
        openHUDButton = new javax.swing.JButton();
        ctrlAtlDelHUDButton = new javax.swing.JButton();
        stopHUDButton = new javax.swing.JButton();
        syncHUDButton = new javax.swing.JButton();
        dragHUDButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(231, 230, 230));

        toggleHUDButton.setBackground(new java.awt.Color(231, 230, 230));
        toggleHUDButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/jdesktop/wonderland/modules/tightvncviewer/client/resources/TightVNCViewerDock32x32.png"))); // NOI18N
        toggleHUDButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        toggleHUDButton.setBorderPainted(false);
        toggleHUDButton.setMargin(new java.awt.Insets(0, -4, 0, -4));
        toggleHUDButton.setOpaque(true);
        toggleHUDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleHUDButtonActionPerformed(evt);
            }
        });

        openHUDButton.setBackground(new java.awt.Color(231, 230, 230));
        openHUDButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/jdesktop/wonderland/modules/tightvncviewer/client/resources/TightVNCViewerOpen32x32.png"))); // NOI18N
        openHUDButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        openHUDButton.setBorderPainted(false);
        openHUDButton.setMargin(new java.awt.Insets(0, -4, 0, -4));
        openHUDButton.setOpaque(true);
        openHUDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openHUDButtonActionPerformed(evt);
            }
        });

        ctrlAtlDelHUDButton.setBackground(new java.awt.Color(231, 230, 230));
        ctrlAtlDelHUDButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/jdesktop/wonderland/modules/tightvncviewer/client/resources/TightVNCViewerCtrlAltDel32x32.png"))); // NOI18N
        ctrlAtlDelHUDButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        ctrlAtlDelHUDButton.setBorderPainted(false);
        ctrlAtlDelHUDButton.setMargin(new java.awt.Insets(0, -4, 0, -4));
        ctrlAtlDelHUDButton.setOpaque(true);
        ctrlAtlDelHUDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctrlAtlDelHUDButtonActionPerformed(evt);
            }
        });

        stopHUDButton.setBackground(new java.awt.Color(231, 230, 230));
        stopHUDButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/jdesktop/wonderland/modules/tightvncviewer/client/resources/TightVNCViewerClose32x32.png"))); // NOI18N
        stopHUDButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        stopHUDButton.setBorderPainted(false);
        stopHUDButton.setMargin(new java.awt.Insets(0, -4, 0, -4));
        stopHUDButton.setOpaque(true);
        stopHUDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopHUDButtonActionPerformed(evt);
            }
        });

        syncHUDButton.setBackground(new java.awt.Color(231, 230, 230));
        syncHUDButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/jdesktop/wonderland/modules/tightvncviewer/client/resources/TightVNCViewerSyncedYes32x32.png"))); // NOI18N
        syncHUDButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        syncHUDButton.setBorderPainted(false);
        syncHUDButton.setMargin(new java.awt.Insets(0, -4, 0, -4));
        syncHUDButton.setOpaque(true);
        syncHUDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                syncHUDButtonActionPerformed(evt);
            }
        });

        dragHUDButton.setBackground(new java.awt.Color(231, 230, 230));
        dragHUDButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/jdesktop/wonderland/modules/tightvncviewer/client/resources/TightVNCViewerDrag32x32.png"))); // NOI18N
        dragHUDButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        dragHUDButton.setBorderPainted(false);
        dragHUDButton.setMargin(new java.awt.Insets(0, -4, 0, -4));
        dragHUDButton.setOpaque(true);
        dragHUDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dragHUDButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(toggleHUDButton)
                .add(0, 0, 0)
                .add(openHUDButton)
                .add(0, 0, 0)
                .add(ctrlAtlDelHUDButton)
                .add(0, 0, 0)
                .add(stopHUDButton)
                .add(0, 0, 0)
                .add(syncHUDButton)
                .add(0, 0, 0)
                .add(dragHUDButton))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(toggleHUDButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 38, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(openHUDButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 38, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(syncHUDButton)
                    .add(dragHUDButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 38, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(ctrlAtlDelHUDButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 38, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(stopHUDButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 38, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void toggleHUDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleHUDButtonActionPerformed
        Iterator<TightVNCViewerToolListener> iter = cellMenuListeners.iterator();
        while (iter.hasNext()) {
            TightVNCViewerToolListener listener = iter.next();
            listener.toggleHUD();
        }
}//GEN-LAST:event_toggleHUDButtonActionPerformed

    private void openHUDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openHUDButtonActionPerformed
        Iterator<TightVNCViewerToolListener> iter = cellMenuListeners.iterator();
        while (iter.hasNext()) {
            TightVNCViewerToolListener listener = iter.next();
            listener.openConnection();
        }
    }//GEN-LAST:event_openHUDButtonActionPerformed

    private void dragHUDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dragHUDButtonActionPerformed
        Iterator<TightVNCViewerToolListener> iter = cellMenuListeners.iterator();
        while (iter.hasNext()) {
            TightVNCViewerToolListener listener = iter.next();
            // TODO: implement drag
        }
    }//GEN-LAST:event_dragHUDButtonActionPerformed

    private void syncHUDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_syncHUDButtonActionPerformed
        Iterator<TightVNCViewerToolListener> iter = cellMenuListeners.iterator();
        while (iter.hasNext()) {
            TightVNCViewerToolListener listener = iter.next();
            listener.sync();
        }
    }//GEN-LAST:event_syncHUDButtonActionPerformed

    private void stopHUDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopHUDButtonActionPerformed
        Iterator<TightVNCViewerToolListener> iter = cellMenuListeners.iterator();
        while (iter.hasNext()) {
            TightVNCViewerToolListener listener = iter.next();
            listener.closeConnection();
        }
    }//GEN-LAST:event_stopHUDButtonActionPerformed

    private void ctrlAtlDelHUDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctrlAtlDelHUDButtonActionPerformed
        Iterator<TightVNCViewerToolListener> iter = cellMenuListeners.iterator();
        while (iter.hasNext()) {
            TightVNCViewerToolListener listener = iter.next();
            listener.sendCtrlAltDel();
        }
    }//GEN-LAST:event_ctrlAtlDelHUDButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ctrlAtlDelHUDButton;
    private javax.swing.JButton dragHUDButton;
    private javax.swing.JButton openHUDButton;
    private javax.swing.JButton stopHUDButton;
    private javax.swing.JButton syncHUDButton;
    private javax.swing.JButton toggleHUDButton;
    // End of variables declaration//GEN-END:variables
}
