/**
 * Open Wonderland
 *
 * Copyright (c) 2011, Open Wonderland Foundation, All Rights Reserved
 *
 * Redistributions in source code form must reproduce the above
 * copyright and this condition.
 *
 * The contents of this file are subject to the GNU General Public
 * License, Version 2 (the "License"); you may not use this file
 * except in compliance with the License. A copy of the License is
 * available at http://www.opensource.org/licenses/gpl-license.php.
 *
 * The Open Wonderland Foundation designates this particular file as
 * subject to the "Classpath" exception as provided by the Open Wonderland
 * Foundation in the License file that accompanied this code.
 */

/**
 * @author Alexios Akrimpai (akrim777@gmail.com)
 */

package org.jdesktop.wonderland.modules.wexplorer.client;

import javax.swing.*;
import java.awt.event.KeyEvent;
import java.io.File;

public class MainPanel extends javax.swing.JPanel {

    /** Creates new form MainPanel */
    public MainPanel() {
        initComponents();

        //Make the tooltip appear for 20 seconds
        ToolTipManager.sharedInstance().setDismissDelay(20000);
    }

    // Few setters for the details panel
    public void setAuthor(String text) {
        detailsAuthor.setText(text);
    }

    public void setRating(String text) {
        detailsRating.setText(text);
    }

    public void setFormats(String text) {
        detailsFormats.setText(text);
    }

    public void setTitle(String text) {
        detailsTitle.setText(text);
    }

    //a getter for download list so it can be set in Warehouse
    public JList getDownloadList() {
        return downloadList;
    }

    public JButton getDownloadButton() {
        return downloadButton;
    }

    public void setImportButtons(boolean b) {
        dPanelImportButton.setEnabled(b);
        mPanelImportButton.setEnabled(b);
    }

    public JProgressBar getPBar() {
        return pBar;
    }

    public JProgressBar getDownloadPBar() {
        return downloadPBar;
    }

    public void chooseFileAndNavigate() {
        localDirChooser.showOpenDialog(this);
        File file = localDirChooser.getSelectedFile();
        if (file != null) {
            Warehouse.instance.setLocalDir(file.toString());
            localDirTextField.setText(Warehouse.instance.getLocalDir());
            localDirTextField2.setText(Warehouse.instance.getLocalDir());
            Warehouse.instance.navigateLocal();
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        modelDialog = new javax.swing.JDialog();
        modelDialogExit = new javax.swing.JButton();
        downloadButton = new javax.swing.JButton();
        dPanelImportButton = new javax.swing.JButton();
        downloadPBar = new javax.swing.JProgressBar();
        jScrollPane5 = new javax.swing.JScrollPane();
        downloadList = new javax.swing.JList();
        jLabel6 = new javax.swing.JLabel();
        localDirChooser = new javax.swing.JFileChooser();
        buttonGroup1 = new javax.swing.ButtonGroup();
        noLocalDirDialog = new javax.swing.JDialog();
        localDirTextField2 = new javax.swing.JTextField();
        changeLocalDir1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        mainTabbledPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        searchBar = new javax.swing.JTextField();
        modelsPerPageTextField = new javax.swing.JTextField();
        lastPage = new javax.swing.JButton();
        nextPage = new javax.swing.JButton();
        currentPageTextField = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        modelsList = new javax.swing.JList();
        searchButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        localDirTextField = new javax.swing.JTextField();
        changeLocalDir = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        localModelsList = new javax.swing.JList();
        installButton = new javax.swing.JButton();
        mPanelImportButton = new javax.swing.JButton();
        pBar = new javax.swing.JProgressBar();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lastSearchesList = new javax.swing.JList();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        detailsTitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        detailsAuthor = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        detailsRating = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        detailsFormats = new javax.swing.JLabel();

        modelDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        modelDialog.setResizable(false);

        modelDialogExit.setText("Exit");
        modelDialogExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dialogExitActionPerformed(evt);
            }
        });

        downloadButton.setText("Download");
        downloadButton.setEnabled(false);
        downloadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downloadButtonActionPerformed(evt);
            }
        });

        dPanelImportButton.setText("Import");
        dPanelImportButton.setEnabled(false);
        dPanelImportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dPanelImportButtonActionPerformed(evt);
            }
        });

        downloadPBar.setStringPainted(true);

        downloadList.setFont(new java.awt.Font("Tahoma", 0, 14));
        downloadList.setModel(Warehouse.instance.getDownloadModels());
        jScrollPane5.setViewportView(downloadList);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("<html>Choose file <br> format<html>");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout modelDialogLayout = new javax.swing.GroupLayout(modelDialog.getContentPane());
        modelDialog.getContentPane().setLayout(modelDialogLayout);
        modelDialogLayout.setHorizontalGroup(
            modelDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modelDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(modelDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(modelDialogLayout.createSequentialGroup()
                        .addComponent(downloadButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dPanelImportButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(downloadPBar, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(modelDialogExit, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        modelDialogLayout.setVerticalGroup(
            modelDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(modelDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(modelDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                    .addGroup(modelDialogLayout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(modelDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(downloadButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dPanelImportButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(downloadPBar, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                            .addComponent(modelDialogExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );

        localDirChooser.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
        localDirChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localDirChooserActionPerformed(evt);
            }
        });

        noLocalDirDialog.setIconImage(null);

        localDirTextField2.setEditable(false);

        changeLocalDir1.setText("Change");
        changeLocalDir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeLocalDir1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel7.setText("Select local model directory");

        jButton1.setText("Continue");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout noLocalDirDialogLayout = new javax.swing.GroupLayout(noLocalDirDialog.getContentPane());
        noLocalDirDialog.getContentPane().setLayout(noLocalDirDialogLayout);
        noLocalDirDialogLayout.setHorizontalGroup(
            noLocalDirDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noLocalDirDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(noLocalDirDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(noLocalDirDialogLayout.createSequentialGroup()
                        .addComponent(localDirTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(changeLocalDir1))
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        noLocalDirDialogLayout.setVerticalGroup(
            noLocalDirDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noLocalDirDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(noLocalDirDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(localDirTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changeLocalDir1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        mainTabbledPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mainTabbledPaneStateChanged(evt);
            }
        });

        searchBar.setText("Keyword / Model ID");
        searchBar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                searchBarFocusGained(evt);
            }
        });
        searchBar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchListener(evt);
            }
        });

        modelsPerPageTextField.setText(Warehouse.instance.getResultsPerPage()+"");
        modelsPerPageTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                modelsPerPageTextFieldFocusLost(evt);
            }
        });

        lastPage.setText("<");
        lastPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastPageActionPerformed(evt);
            }
        });

        nextPage.setText(">");
        nextPage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextPageActionPerformed(evt);
            }
        });

        currentPageTextField.setText("1");
        currentPageTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentPageTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchBar, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(modelsPerPageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastPage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(currentPageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nextPage))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(searchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(nextPage)
                .addComponent(currentPageTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addComponent(lastPage)
                .addComponent(modelsPerPageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        modelsList.setModel(Warehouse.instance.getModels());
        modelsList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        modelsList.setCellRenderer(new ListRenderer());
        modelsList.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        modelsList.setLayoutOrientation(javax.swing.JList.HORIZONTAL_WRAP);
        modelsList.setVerifyInputWhenFocusTarget(false);
        modelsList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                modelsListValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(modelsList);
        modelsList.setVisibleRowCount(0);

        jScrollPane6.setViewportView(jScrollPane3);

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchButton)
                .addContainerGap())
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE))
        );

        mainTabbledPane.addTab("Warehouse", jPanel1);

        jLabel5.setText("Local models");

        localDirTextField.setEditable(false);

        changeLocalDir.setText("Change");
        changeLocalDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeLocalDirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(localDirTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(changeLocalDir, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changeLocalDir, 0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 17, Short.MAX_VALUE)
                    .addComponent(localDirTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        localModelsList.setModel(Warehouse.instance.getLocalModels());
        localModelsList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        localModelsList.setCellRenderer(new ListRenderer());
        localModelsList.setLayoutOrientation(javax.swing.JList.HORIZONTAL_WRAP);
        localModelsList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                localModelsListValueChanged(evt);
            }
        });
        jScrollPane7.setViewportView(localModelsList);
        requestFocus();
        localModelsList.setVisibleRowCount(0);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE))
        );

        mainTabbledPane.addTab("Local", jPanel3);

        installButton.setText("Download");
        installButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                installButtonActionPerformed(evt);
            }
        });

        mPanelImportButton.setText("Import");
        mPanelImportButton.setEnabled(false);
        mPanelImportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mPanelImportButtonActionPerformed(evt);
            }
        });

        pBar.setStringPainted(true);

        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        lastSearchesList.setModel(Warehouse.instance.getLastSearches());
        lastSearchesList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lastSearchesList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lastSearchesListValueChanged(evt);
            }
        });
        lastSearchesList.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lastSearchesListKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(lastSearchesList);

        jLabel9.setText("Recent searches");

        jLabel10.setText("Details");

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Title:");

        detailsTitle.setFont(new java.awt.Font("Tahoma", 2, 11));
        detailsTitle.setText("none");

        jLabel2.setText("Author:");

        detailsAuthor.setFont(new java.awt.Font("Tahoma", 2, 11));
        detailsAuthor.setText("none");

        jLabel3.setText("Rating");

        detailsRating.setFont(new java.awt.Font("Tahoma", 2, 11));
        detailsRating.setText("none");

        jLabel4.setText("Formats:");

        detailsFormats.setFont(new java.awt.Font("Tahoma", 2, 11));
        detailsFormats.setText("none");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(detailsTitle)
                    .addComponent(detailsAuthor)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(detailsRating)
                    .addComponent(jLabel4)
                    .addComponent(detailsFormats))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addComponent(detailsTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addComponent(detailsAuthor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(3, 3, 3)
                .addComponent(detailsRating)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detailsFormats)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainTabbledPane, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(installButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mPanelImportButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pBar, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mainTabbledPane, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(mPanelImportButton, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                                    .addComponent(pBar, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                                    .addComponent(jButton3))
                                .addGap(12, 12, 12))
                            .addComponent(installButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dialogExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dialogExitActionPerformed
        // TODO add your handling code here:
        modelDialog.dispose();
    }//GEN-LAST:event_dialogExitActionPerformed

    private void localDirChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localDirChooserActionPerformed
//        Warehouse.instance.setLocalDir(localDirTextField.getText());
//        Warehouse.instance.navigateLocal();
//        System.out.println("Local dir: " + Warehouse.instance.getLocalDir());
    }//GEN-LAST:event_localDirChooserActionPerformed

    private void lastSearchesListKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lastSearchesListKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_lastSearchesListKeyTyped

    private void lastSearchesListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lastSearchesListValueChanged
        // TODO add your handling code here:
        if (!evt.getValueIsAdjusting()) {
            searchBar.setText(lastSearchesList.getSelectedValue().toString());
        }
    }//GEN-LAST:event_lastSearchesListValueChanged

    private void downloadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downloadButtonActionPerformed
        // TODO add your handling code here:
        if (localDirTextField.getText().equals("")) {
//            JOptionPane.showMessageDialog(this,
//                    "Select local file directory.",
//                    "Error",
//                    JOptionPane.ERROR_MESSAGE);

            noLocalDirDialog.setVisible(true);
            noLocalDirDialog.pack();
            noLocalDirDialog.setLocationRelativeTo(null);
        } else {
            Warehouse.instance.downloadModel(Warehouse.instance.getSelectedModel().getSources().get("kmz"),
                    localDirTextField.getText() + File.separator + Warehouse.instance.getSelectedModel().getId()
                    + File.separator, this);
        }
    }//GEN-LAST:event_downloadButtonActionPerformed

    private void dPanelImportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dPanelImportButtonActionPerformed
        // TODO add your handling code here:
        String path = localDirTextField.getText() + File.separator + Warehouse.instance.getSelectedModel().getId()
                + File.separator + Warehouse.instance.getSelectedModel().getTitle() + ".kmz";
        Warehouse.instance.importModel(path);
    }//GEN-LAST:event_dPanelImportButtonActionPerformed

    private void installButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_installButtonActionPerformed
        modelDialog.setVisible(true);
        modelDialog.pack();
        modelDialog.setLocationRelativeTo(null);
}//GEN-LAST:event_installButtonActionPerformed

    private void mPanelImportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mPanelImportButtonActionPerformed
        // TODO add your handling code here:
        String path = localDirTextField.getText() + File.separator + Warehouse.instance.getSelectedModel().getId()
                + File.separator + Warehouse.instance.getSelectedModel().getTitle() + ".kmz";
        Warehouse.instance.importModel(path);
}//GEN-LAST:event_mPanelImportButtonActionPerformed

    private void mainTabbledPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mainTabbledPaneStateChanged
        // TODO add your handling code here:
        if (mainTabbledPane.getSelectedIndex() == 1) { //Local tab
            Warehouse.instance.navigateLocal();
        }
}//GEN-LAST:event_mainTabbledPaneStateChanged

    private void changeLocalDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeLocalDirActionPerformed
        // TODO add your handling code here:
        chooseFileAndNavigate();
}//GEN-LAST:event_changeLocalDirActionPerformed

    private void modelsListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_modelsListValueChanged

        if (!evt.getValueIsAdjusting() && !Warehouse.instance.getModels().isEmpty()) {
            if (modelsList.getSelectedValue() != null) {
                WHModel o = (WHModel) modelsList.getSelectedValue();
                Warehouse.instance.setSelectedModel(o.getId(), Warehouse.instance.getModels(), this);
            }
        }
}//GEN-LAST:event_modelsListValueChanged

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        Warehouse.instance.addLastSearch(this.searchBar.getText());
        Warehouse.instance.navigate(this.searchBar.getText(),
                Integer.parseInt(this.currentPageTextField.getText()), this);
}//GEN-LAST:event_searchButtonActionPerformed

    private void currentPageTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentPageTextFieldActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_currentPageTextFieldActionPerformed

    private void nextPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextPageActionPerformed
        int value = Integer.parseInt(currentPageTextField.getText()) + 1;
        currentPageTextField.setText(value + "");
        Warehouse.instance.navigate(searchBar.getText(), value, this);
}//GEN-LAST:event_nextPageActionPerformed

    private void lastPageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastPageActionPerformed
        int value = Integer.parseInt(currentPageTextField.getText()) - 1;
        if (value > 0) {
            currentPageTextField.setText(value + "");
            Warehouse.instance.navigate(searchBar.getText(), value, this);
        }
}//GEN-LAST:event_lastPageActionPerformed

    private void modelsPerPageTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_modelsPerPageTextFieldFocusLost
        Warehouse.instance.setResultsPerPage(Integer.parseInt(modelsPerPageTextField.getText()));
}//GEN-LAST:event_modelsPerPageTextFieldFocusLost

    private void searchListener(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchListener
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Warehouse.instance.addLastSearch(this.searchBar.getText());
            Warehouse.instance.navigate(this.searchBar.getText(),
                    Integer.parseInt(this.currentPageTextField.getText()), this);
        }
}//GEN-LAST:event_searchListener

    private void searchBarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchBarFocusGained
        searchBar.setSelectionStart(0);
}//GEN-LAST:event_searchBarFocusGained

    private void localModelsListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_localModelsListValueChanged
        if (!evt.getValueIsAdjusting()) {
            if (localModelsList.getSelectedValue() != null) {
                WHModel o = (WHModel) localModelsList.getSelectedValue();
                Warehouse.instance.setSelectedModel(o.getId(), Warehouse.instance.getLocalModels(), this);
            }
        }
}//GEN-LAST:event_localModelsListValueChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
//        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void changeLocalDir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeLocalDir1ActionPerformed
        chooseFileAndNavigate();
}//GEN-LAST:event_changeLocalDir1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        noLocalDirDialog.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton changeLocalDir;
    private javax.swing.JButton changeLocalDir1;
    private javax.swing.JTextField currentPageTextField;
    private javax.swing.JButton dPanelImportButton;
    private javax.swing.JLabel detailsAuthor;
    private javax.swing.JLabel detailsFormats;
    private javax.swing.JLabel detailsRating;
    private javax.swing.JLabel detailsTitle;
    private javax.swing.JButton downloadButton;
    private javax.swing.JList downloadList;
    private javax.swing.JProgressBar downloadPBar;
    private javax.swing.JButton installButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JButton lastPage;
    private javax.swing.JList lastSearchesList;
    private javax.swing.JFileChooser localDirChooser;
    private javax.swing.JTextField localDirTextField;
    private javax.swing.JTextField localDirTextField2;
    private javax.swing.JList localModelsList;
    private javax.swing.JButton mPanelImportButton;
    private javax.swing.JTabbedPane mainTabbledPane;
    private javax.swing.JDialog modelDialog;
    private javax.swing.JButton modelDialogExit;
    private javax.swing.JList modelsList;
    private javax.swing.JTextField modelsPerPageTextField;
    private javax.swing.JButton nextPage;
    private javax.swing.JDialog noLocalDirDialog;
    private javax.swing.JProgressBar pBar;
    private javax.swing.JTextField searchBar;
    private javax.swing.JButton searchButton;
    // End of variables declaration//GEN-END:variables
}
