/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EventEditor.java
 *
 * Created on Jan 11, 2010, 5:40:46 AM
 */
package org.jdesktop.wonderland.modules.cmu.client.ui.events;

import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.List;
import org.jdesktop.wonderland.modules.cmu.client.CMUCell;
import org.jdesktop.wonderland.modules.cmu.common.events.EventResponseList;
import org.jdesktop.wonderland.modules.cmu.common.events.EventResponsePair;

/**
 *
 * @author kevin
 */
public class EventEditor extends javax.swing.JFrame {

    private final CMUCell parentCell;
    private final List<SingleEventPanel> eventPanels = new ArrayList<SingleEventPanel>();

    /** Creates new form EventEditor */
    public EventEditor(CMUCell parentCell) {
        initComponents();
        this.parentCell = parentCell;
        GridLayout eventLayout = (GridLayout) this.eventsPanel.getLayout();
        eventLayout.setColumns(1);

        this.eventsPanel.setLayout(new GridLayout(0, 1));

        // Add events from parent cell
        for (EventResponsePair pair : parentCell.getEventList()) {
            SingleEventPanel panel = this.addEvent();
            panel.setEventAndResponse(pair);
        }
        this.pack();
    }

    public SingleEventPanel addEvent() {
        SingleEventPanel panel = new SingleEventPanel(this);
        this.eventsPanel.add(panel);
        this.eventPanels.add(panel);
        this.pack();
        this.repaint();

        return panel;
    }

    public void removeEvent(SingleEventPanel event) {
        this.eventsPanel.remove(event);
        this.eventPanels.remove(event);
        this.pack();
        this.repaint();
    }

    public CMUCell getParentCell() {
        return parentCell;
    }


    public EventResponseList getEventResponseList() {
        EventResponseList list = new EventResponseList();

        for (SingleEventPanel panel : this.eventPanels) {
            EventResponsePair pair = panel.getEventAndResponse();
            if (pair != null) {
                list.add(pair);
            }
        }

        return list;
    }

    public void applyList() {
        this.getParentCell().setEventList(this.getEventResponseList());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cancelButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        eventsPanel = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonPressed(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonPressed(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        eventsPanel.setPreferredSize(new java.awt.Dimension(100, 100));
        eventsPanel.setLayout(new java.awt.GridLayout());
        jScrollPane1.setViewportView(eventsPanel);

        addButton.setText("New Event");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(okButton)
                    .addComponent(addButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonPressed
        this.applyList();
        this.setVisible(false);
    }//GEN-LAST:event_okButtonPressed

    private void cancelButtonPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonPressed
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonPressed

    private void addButtonPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonPressed
        this.addEvent();
    }//GEN-LAST:event_addButtonPressed

    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new EventEditor(null).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel eventsPanel;
    private javax.swing.JButton okButton;
    // End of variables declaration//GEN-END:variables
}
