/**
 * Project Wonderland
 *
 * Copyright (c) 2004-2009, Sun Microsystems, Inc., All Rights Reserved
 *
 * Redistributions in source code form must reproduce the above
 * copyright and this condition.
 *
 * The contents of this file are subject to the GNU General Public
 * License, Version 2 (the "License"); you may not use this file
 * except in compliance with the License. A copy of the License is
 * available at http://www.opensource.org/licenses/gpl-license.php.
 *
 * Sun designates this particular file as subject to the "Classpath"
 * exception as provided by Sun in the License file that accompanied
 * this code.
 */
package org.jdesktop.wonderland.modules.apptest.client;

import javax.swing.JWindow;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 * The JPanel for the App Test.
 * @author Ronny Standtke <ronny.standtke@fhnw.ch>
 */
public class TestPanel extends javax.swing.JPanel {

    private JFrame frame;

    private Container container;

    private boolean started;

    public interface Container {
        public void startTest();
        public void stopTest();
    }

    /** Creates new form TestPanel */
    public TestPanel() {
        initComponents();
    }

    public void setContainer (Container container) {
        this.container = container;
    }

    public void setFrame(JFrame frame) {
        this.frame = frame;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        startStopButton = new javax.swing.JButton();

        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        setLayout(new java.awt.GridBagLayout());

        startStopButton.setText("Start Test");
        startStopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startStopButtonActionPerformed(evt);
            }
        });
        add(startStopButton, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
        //System.out.println("Panel focus Gained");
    }//GEN-LAST:event_formFocusGained

    private void startStopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startStopButtonActionPerformed
        if (!started) {
            // Start test
            started = true;
            startStopButton.setText("Stop Test");
            if (container != null) {
                SwingUtilities.invokeLater(new Runnable () {
                    public void run () {
                        container.startTest();
                    }
                });
            }
        } else {
            // Stop test
            started = false;
            startStopButton.setText("Start Test");
            if (container != null) {
                SwingUtilities.invokeLater(new Runnable () {
                    public void run () {
                        container.stopTest();
                    }
                });
            }
        }
    }//GEN-LAST:event_startStopButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton startStopButton;
    // End of variables declaration//GEN-END:variables

    public static void main(String args[]) {
        JWindow j = new JWindow();
        //JFrame j = new JFrame();
//        j.addMouseMotionListener(new MouseMotionAdapter() {
//           public void mouseMoved(java.awt.event.MouseEvent evt) {
//                System.out.println(evt);
//            }
//        });
        System.out.println(j.getLayout());
        j.add(new TestPanel());
        j.pack();
        j.setVisible(true);
    }
}
