/**
 * Project Wonderland
 *
 * $URL$
 *
 * Copyright (c) 2004-2008, Sun Microsystems, Inc., All Rights Reserved
 *
 * Redistributions in source code form must reproduce the above
 * copyright and this condition.
 *
 * The contents of this file are subject to the GNU General Public
 * License, Version 2 (the "License"); you may not use this file
 * except in compliance with the License. A copy of the License is
 * available at http://www.opensource.org/licenses/gpl-license.php.
 *
 * $Rev$
 * $Date$
 * $Author$
 */
package com.sun.labs.miw.client.cell;

import com.sun.labs.miw.common.MIWTrack;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author  root
 */
public class PlaylistViewer extends javax.swing.JFrame {
    
    /** Creates new form PlaylistView */
    public PlaylistViewer() {
        initComponents();
        setVisible(UI.showWindows);
    }
    void setNowPlaying() {
    }
    void updateView() {
       List<MIWTrack> tracks = UI.playlist.tracks;
       int numTracks = tracks.size();
       String[][] data = new String[numTracks][5];
       for (int j = 0; j<numTracks; j++) {
           MIWTrack t = tracks.get(j);
           data[j][0] =String.format("%03d",j);
           data[j][1] = t.getAlbum();
           data[j][2] = t.getArtist();
           data[j][3] = t.getName();
           data[j][4] = t.getTrackId();
       }
       TracksTable.setModel(new DefaultTableModel(data,new String[] {"","Album","Artist","Name","ID"}));;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TablePopupMenu = new javax.swing.JPopupMenu();
        ViewAlbum = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        TracksTable = new javax.swing.JTable();

        ViewAlbum.setText("View Album");
        ViewAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewAlbumActionPerformed(evt);
            }
        });
        TablePopupMenu.add(ViewAlbum);

        setTitle("Playlist");

        TracksTable.setComponentPopupMenu(TablePopupMenu);
        TracksTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "", "Album", "Artist", "Name", "ID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TracksTable);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 275, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ViewAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewAlbumActionPerformed
        int row = TracksTable.getSelectedRow();
        MIWTrack track = UI.playlist.tracks.get(row);
        Album album = UI.albums.get(track.getAlbum());
        UI.albumCloudCell.requestAlbumInfo(album.name);
    }//GEN-LAST:event_ViewAlbumActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu TablePopupMenu;
    private javax.swing.JTable TracksTable;
    private javax.swing.JMenuItem ViewAlbum;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
}
