/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ErrorWindow.java
 *
 * Created on Jun 9, 2011, 5:02:01 PM
 */

package org.jdesktop.wonderland.modules.ezscript.client;

import java.awt.Dimension;
import java.util.List;
import javax.swing.JTextArea;
import org.jdesktop.wonderland.client.hud.HUDComponent;

/**
 *
 * @author JagWire
 */
public class ErrorWindow extends javax.swing.JPanel {

    /** Creates new form ErrorWindow */
    private HUDComponent hudComponent;
    private ErrorWindow() {
        initComponents();
        this.setPreferredSize(new Dimension(600, 500));
        this.setMinimumSize(new Dimension(600, 500));
    }

    public ErrorWindow(String summary, List<String> solutions) {
        this();

        messageLabel.setText(constructSummary(summary, solutions));
    }

    private String constructListItem(String in) {        
        return "<li>"+in+"</li>";
    }

    private String constructList(List<String> items) {
        String list = "<ul>";

        for(String item: items) {
            list += constructListItem(item);
        }
        return list+"</ul>";
    }

    private String constructSummary(String summary, List<String> solutions) {
        String markup = "<html>";
        markup += summary;
        markup += "<p><p>";
        markup += constructList(solutions);     
        return markup+"</html>";
    }

    public JTextArea getDetailsArea() {
        return detailsArea;
    }

    public void setHUDComponent(HUDComponent component) {
        hudComponent = component;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        closeButton = new javax.swing.JButton();
        tabbedPanel = new javax.swing.JTabbedPane();
        summaryPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        messageLabel = new javax.swing.JLabel();
        detailsPanel = new javax.swing.JPanel();
        scrollpane = new javax.swing.JScrollPane();
        detailsArea = new javax.swing.JTextArea();

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        headerLabel.setText("Uh oh, looks like something went wrong...");

        org.jdesktop.layout.GroupLayout summaryPanelLayout = new org.jdesktop.layout.GroupLayout(summaryPanel);
        summaryPanel.setLayout(summaryPanelLayout);
        summaryPanelLayout.setHorizontalGroup(
            summaryPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(summaryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(summaryPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(headerLabel)
                    .add(messageLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 355, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        summaryPanelLayout.setVerticalGroup(
            summaryPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(summaryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(headerLabel)
                .add(18, 18, 18)
                .add(messageLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 189, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        tabbedPanel.addTab("Summary", summaryPanel);

        detailsArea.setColumns(20);
        detailsArea.setRows(5);
        scrollpane.setViewportView(detailsArea);

        org.jdesktop.layout.GroupLayout detailsPanelLayout = new org.jdesktop.layout.GroupLayout(detailsPanel);
        detailsPanel.setLayout(detailsPanelLayout);
        detailsPanelLayout.setHorizontalGroup(
            detailsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(scrollpane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
        );
        detailsPanelLayout.setVerticalGroup(
            detailsPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(scrollpane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
        );

        tabbedPanel.addTab("Details", detailsPanel);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(tabbedPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
                    .add(closeButton))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(tabbedPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(closeButton))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        if(hudComponent == null) {
            return;
        }
        hudComponent.setVisible(false);
    }//GEN-LAST:event_closeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JTextArea detailsArea;
    private javax.swing.JPanel detailsPanel;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JScrollPane scrollpane;
    private javax.swing.JPanel summaryPanel;
    private javax.swing.JTabbedPane tabbedPanel;
    // End of variables declaration//GEN-END:variables

}
