/**
 * Open Wonderland
 *
 * Copyright (c) 2011, Open Wonderland Foundation, All Rights Reserved
 *
 * Redistributions in source code form must reproduce the above
 * copyright and this condition.
 *
 * The contents of this file are subject to the GNU General Public
 * License, Version 2 (the "License"); you may not use this file
 * except in compliance with the License. A copy of the License is
 * available at http://www.opensource.org/licenses/gpl-license.php.
 *
 * The Open Wonderland Foundation designates this particular file as
 * subject to the "Classpath" exception as provided by the Open Wonderland
 * Foundation in the License file that accompanied this code.
 */

package org.jdesktop.wonderland.modules.poster.client;

/**
 *
 * @author Bernard Horan
 */
public class PosterPanel extends javax.swing.JPanel {
    private PosterCell cell;

    /** Creates new form PosterPanel */
    public PosterPanel() {
        initComponents();
    }

    PosterPanel(PosterCell cell) {
        this();
        this.cell = cell;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        posterLabel = new javax.swing.JLabel();

        posterLabel.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        posterLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        posterLabel.setText("jLabel1");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(posterLabel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(posterLabel)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel posterLabel;
    // End of variables declaration//GEN-END:variables

    void updateLabel() {
        posterLabel.setText(cell.getPosterText());
    }

}
