print 'Hello from jython - mouse script' ;
print name;
MyClass.testMethod("rabbit");
stateString[0] = "abracadabra";
name = "fubar";
print name;
print stateString[0];
stateString[0] = "snapz";
print stateString[0];
testInt = 1006;
