/**
 * Project Wonderland
 *
 * Copyright (c) 2004-2010, Sun Microsystems, Inc., All Rights Reserved
 *
 * Redistributions in source code form must reproduce the above
 * copyright and this condition.
 *
 * The contents of this file are subject to the GNU General Public
 * License, Version 2 (the "License"); you may not use this file
 * except in compliance with the License. A copy of the License is
 * available at http://www.opensource.org/licenses/gpl-license.php.
 *
 * Sun designates this particular file as subject to the "Classpath"
 * exception as provided by Sun in the License file that accompanied
 * this code.
 */

package org.jdesktop.wonderland.modules.scriptingPoster.client;

import java.awt.Dimension;
import java.awt.Graphics2D;
import java.awt.Image;
import java.util.ResourceBundle;
import javax.swing.ImageIcon;

/**
 * Dialogue box for entering the text for a poster
 * @author  Bernard Horan
 */
public class ScriptingPosterForm extends javax.swing.JFrame {
    private static final ResourceBundle bundle = ResourceBundle.getBundle("org/jdesktop/wonderland/modules/scriptingPoster/client/resources/Bundle");
    
    private ScriptingPosterCell posterCell;

    public ScriptingPosterForm() {
        initComponents();
        textArea.setText("");
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
    }
    
    /** Creates new form PosterForm
     * @param posterCell the cell that initiates this dialogue box
     */
    public ScriptingPosterForm(ScriptingPosterCell posterCell) {
        this();
        this.posterCell = posterCell;
    }

    void updateForm() {
        if (posterCell == null) {
            return;
        }
        textArea.setText(posterCell.getPosterText());
        billboardModeCB.setSelected(posterCell.getBillboardMode());
        updatePreviewLabel();
    }

    private void updatePreviewLabel() {
        previewLabel.setIcon(null);
        ImageIcon icon = new ImageIcon(getPreviewImage());
        previewLabel.setIcon(icon);       
    }

    Image getPreviewImage() {
        if (textArea.getText().isEmpty()) {
            return null;
        }       
        previewLabel.setText(textArea.getText());
        Dimension size = previewLabel.getPreferredSize();
        previewLabel.setSize(size);
        Image image = createImage(size.width, size.height);
        Graphics2D g2d = (Graphics2D) image.getGraphics();
        g2d.setFont(getFont());
        previewLabel.paint(g2d);
        previewLabel.setText("");
        g2d.dispose();
        return image;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        doneButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        previewLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        previewButton = new javax.swing.JButton();
        billboardModeCB = new javax.swing.JCheckBox();

        setTitle(bundle.getString("ENTER_POSTER_TEXT")); // NOI18N
        setAlwaysOnTop(true);

        doneButton.setText(bundle.getString("OK")); // NOI18N
        doneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doneButtonActionPerformed(evt);
            }
        });

        cancelButton.setText(bundle.getString("CANCEL")); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        previewLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        previewLabel.setText("jLabel1");
        previewLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        previewLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        previewLabel.setOpaque(true);

        textArea.setColumns(20);
        textArea.setRows(5);
        textArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(textArea);

        previewButton.setText(bundle.getString("PREVIEW")); // NOI18N
        previewButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        previewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previewButtonActionPerformed(evt);
            }
        });

        billboardModeCB.setText(bundle.getString("BILLBOARD_MODE")); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(previewLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                            .add(layout.createSequentialGroup()
                                .add(doneButton)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 105, Short.MAX_VALUE)
                                .add(cancelButton))
                            .add(billboardModeCB)))
                    .add(layout.createSequentialGroup()
                        .add(92, 92, 92)
                        .add(previewButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(89, 89, 89)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 149, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(previewButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(previewLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(billboardModeCB)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(doneButton)
                    .add(cancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doneButtonActionPerformed
        posterCell.setPosterText(textArea.getText());
        posterCell.setBillboardMode(billboardModeCB.isSelected());
        setVisible(false);
}//GEN-LAST:event_doneButtonActionPerformed

    private void previewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previewButtonActionPerformed
        updatePreviewLabel();
    }//GEN-LAST:event_previewButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScriptingPosterForm().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox billboardModeCB;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton doneButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton previewButton;
    private javax.swing.JLabel previewLabel;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables


    
}
